version: '3.8'

services: 
    db:
        image: 'postgres:12'
        environment: 
          - POSTGRES_DB=db
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
        ports: 
          - '5432:5432'